### ISSUE TITLE
v4.0-release windows build fails for x86

### ISSUE THREAD

**Issue by reevespaul** [FirebirdSQL/firebird#8975]
This problem is related to VS2017 which is used for all v4 maintenance releases. The problem does not appear with VS2022.

```
ClCompile target) -> 
         ..\..\..\gen\isql\isql.cpp(108): fatal error C1083: Cannot open include file: 'VersionHelpers.h': No such file or directory 
[C:\drone\src\builds\win32\msvc15\isql.vcxproj]
```

And yet the file exists.

And what is more strange is that the x64 build succeeds.

This problem appears to be caused by commit f3941bab on 11 August last year. 

The same build environment succeeds with the previous commit 8b40c3a2 from 7 August. 
In fact the build environment is the same one used for all v4.0 releases up until v4.0.6.

I've looked at the project files and I can't find anything to indicate any difference between the x86 and x64 builds. 

Here is the x86 include path:

```
INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\ATLMFC\include;
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include;
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt
```

and here is the directory output:

```
Z:\FB40\FB4-dev\builds\win32>dir "C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\VersionHelpers.h"
 Volume in drive C has no label.
 Volume Serial Number is 3A1F-1028

 Directory of C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um

22/10/2018  20:38             4,397 VersionHelpers.h
               1 File(s)          4,397 bytes
               0 Dir(s)  26,092,265,472 bytes free
```

**Comment by hvlad** [comment]
Should be fixed in ad0f3074b

**Comment by reevespaul** [comment]
Thanks Vlad

Both Windows builds complete.
